### ISSUE TITLE
Add Netsuite metadata support

### ISSUE THREAD

**Issue by thelesenok** [aabarmin/database-metadata-extractor#20]

**Comment by aabarmin** [comment]
To start with it, a few more tickets need to be done first: 

- [ ] #22 Update Parameters model
- [ ] #24 Update documentation to support new Parameters model
- [ ] #23 Brush-up Gradle dependencies
- [ ] #25 Create a Netsuite module
- [ ] #26 Implement metadata extractors for Netsuite
